#!/bin/bash

echo 'a = Display Date and Time'
echo 'b = List file and directories'
echo 'c = List users logged in'
echo 'd = Check System uptime'
echo -en "\nPlease choose one of the options: "

read choices
case $choices in
	a) date;;
	b) ls;;
	c) who;;
	d) uptime;;
	*) echo Invalid choice -Bye.
esac
