#!/bin/bash

echo '---------------------------------------'
echo 'a = Display date and time'
echo 'b = List file and directories'
echo 'c = List users logged in'
echo 'd = Check System uptime'
echo '---------------------------------------'
echo -n "Please choose on of the options: "


read choices
echo
case $choices in
	a) date;;
	b) ls;;
	c) who;;
	d) uptime;;
	*) echo Invalid choice - Bye.
esac
