#!/bin/bash

count=0
num=10
current_pid=`ps -u | grep "/bin/bash ./while_script" | head -1 | awk '{print $2}'`
echo -e "$current_pid"
while [ $count -lt 10 ]
do
	clear
	echo -e "\n$num seconds left to stop this process $current_pid\n"
	sleep 1
	num=`expr $num - 1`
	count=`expr $count + 1`
done
echo -e "\n$current_pid process is stopped!!\n"

