#!/bin/bash

echo -n "Enter your ip or * to use the prev ip: " 
read var_ip
if [[ $var_ip == "*" ]];
then
	var_ip=$(cat temp_ping)
fi
#echo $var_ip

ping -c1 $var_ip &> /dev/null
if [ $? -eq 0 ]
then
	echo -e "\e[32mOK\e[0m"
else
	echo -e "\e[31mNOT OK\e[0m"
fi

echo $var_ip > temp_ping 2> /dev/null
